import random
from datetime import timedelta

from django.contrib.auth.models import User
from django.contrib.gis.geos import Point
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from django.utils import timezone

from event_manager.models import Event, EventStatus, Place


class Command(BaseCommand):
    help = "Generates random Places and Events."

    def add_arguments(self, parser):
        parser.add_argument("--places", type=int, default=10, help="How many places to create")
        parser.add_argument("--events", type=int, default=50, help="How many events to create")
        parser.add_argument(
            "--author-id",
            type=int,
            default=None,
            help="ID of django.contrib.auth user linked to CustomeUser",
        )

    @transaction.atomic
    def handle(self, *args, **options):
        places_count = options["places"]
        events_count = options["events"]
        author_id = options["author_id"]

        if places_count < 1 or events_count < 1:
            raise CommandError("--places and --events must be positive integers")

        author = self._resolve_author(author_id=author_id)
        places = self._create_places(places_count)
        self._create_events(events_count, author, places)

        self.stdout.write(
            self.style.SUCCESS(
                f"Done. Created {len(places)} places and {events_count} events for author '{author.name}'."
            )
        )

    def _resolve_author(self, author_id=None):
        if author_id is not None:
            try:
                return User.objects.get(user_id=author_id)
            except User.DoesNotExist as exc:
                raise CommandError(
                    "CustomeUser for provided --author-id was not found"
                ) from exc

        existing = User.objects.first()
        if existing:
            return existing

        username = "generator_user"
        email = "generator@example.com"
        user, _ = User.objects.get_or_create(
            username=username,
            defaults={"email": email},
        )
        return user
        

    def _create_places(self, count):
        places = []
        for i in range(count):
            lat = round(random.uniform(-80.0, 80.0), 6)
            lon = round(random.uniform(-170.0, 170.0), 6)
            place, _ = Place.objects.get_or_create(
                name=f"Generated place {i + 1}",
                defaults={"geo_location": Point(lon, lat, srid=4326)},
            )
            places.append(place)
        return places

    def _create_events(self, count, author, places):
        now = timezone.now()
        for i in range(count):
            publish_shift_days = random.randint(-5, 5)
            publish_at = now + timedelta(days=publish_shift_days, hours=random.randint(0, 23))
            starts_at = publish_at + timedelta(days=random.randint(0, 15), hours=random.randint(1, 6))
            ends_at = starts_at + timedelta(hours=random.randint(2, 24))
            status = EventStatus.PUBLISHED if publish_at <= now else EventStatus.DRAFT

            Event.objects.create(
                name=f"Generated event {i + 1}",
                description="Autogenerated event for local development",
                publish_at=publish_at,
                starts_at=starts_at,
                ends_at=ends_at,
                author=author,
                place=random.choice(places),
                rating=random.randint(0, 25),
                status=status,
            )
