# Generated by Django 6.0.4 on 2026-04-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailNotificationConfig',
        ),
    ]
